### ISSUE TITLE
Emails not sent on deployed website

### ISSUE THREAD

**Issue by GhosTHaise** [adrianhajdin/pricewise#5]
Hi there,nodemailer function not work on my deployed website. "sendEmail" function has been called and no error happened on log but no mail has been sent.It works perfectly on localhost server
![image](https://github.com/adrianhajdin/pricewise/assets/68249758/9ca0ca89-93f1-48b6-bec1-57194c20a9c7)

**Comment by UjwalPatel05** [comment]
> Hi there,nodemailer function not work on my deployed website. "sendEmail" function has been called and no error happened on log but no mail has been sent.It works perfectly on localhost server ![image](https://user-images.githubusercontent.com/68249758/276356499-9ca0ca89-93f1-48b6-bec1-57194c20a9c7.png)

I also got the same error. have you found the solution?

**Comment by UjwalPatel05** [comment]
@GhosTHaise You need to remove the callback from the nodemailer sendEmail function otherwise, it does not return a promise... this causes the script in vercel to be terminated earlier hence not email being sent!

**Comment by sathyashiva9** [comment]
I am getting welcome message but there is no message when there is a price drop. Can you help me with it?

**Comment by mohamedaleya** [comment]
On Netlify, Vercel etc it didn't work. However after deploying it on my EC2 VPS it worked like a charm.

The issue is with nodemailer according to multiple replies on similar issues.

**Comment by GhosTHaise** [comment]
> On Netlify, Vercel etc it didn't work. However after deploying it on my EC2 VPS it worked like a charm.
> 
> The issue is with nodemailer according to multiple replies on similar issues.

Thanks it works now !
